information:
  label: Sciences Humaines S2
  level: L1
  ects: 4
  coordinator: Steve FRANK & Klervi LE COLLEN

description: |
  ## Introduction
  
  Le but de cette UE est de vous proposer un programme qui vise à développer vos compétences en anglais et en méthodologie de travail.
  
  Cette UE est conçue pour vous aider à renforcer votre capacité à comprendre, analyser, synthétiser des informations, des idées, des concepts et à les communiquer.
  
  ### Objectifs
  
  L'objectif principal de cette UE est de vous préparer à réussir dans un monde professionnel exigeant et en constante évolution, les compétences que vous développerez ici vous seront extrêmement précieuses.
  
  Pour l'anglais, nous mettons l'accent sur la compréhension et l'expression orale, ainsi que la lecture et les résumés de textes.
  
  Pour la méthodologie, l'axe de ce semestre sera la découverte du monde professionnel et la méthode de communication 360.
  
  ### Méthodologie d'enseignement
  
  Ce cours adopte une approche interactive et pratique, avec des exercices, des études de cas, des discussions en groupe et des travaux pratiques.
  
  Vous aurez l'opportunité de mettre en pratique vos compétences tout au long du semestre.
