description: |
  ### Introduction
  
  Le Cycle Préparatoire se compose de 2 années de formation constituées chacune de 2 semestres (souvent abrégés en S1, S2, S3 et S4).
  
  Un semestre est décomposé en Unités d'Enseignement (UE) thématiques. Une UE peut contenir un ou plusieurs ECUE (Elément Constitutif d'Unité d'Enseignement).
  
  Chaque activité est évaluée selon un ou plusieurs des modes suivants :
  - Contrôle en salle (devoir sur Table)
  - Suivi continu (durant les cours)
  - Rendu de projet et/ou de TP
  - Rapport et soutenance
  - Examen partiel (en fin de semestre)
  
  ### Organisation et structure de la formation
  
  La formation est organisée de façon à donner tous les pré-requis nécessaires au cycle ingénieur de l'EPITA.
  
  Les pré-requis s'entendent en termes de connaissances et compétences acquises mais également en termes d'organisation et de savoir-faire.
  
  La suite de ce document décrit pour chaque UE les ECUE qui la composent, avec :  
  - les volumes horaires consacrés :
    - Le volume horaire de face à face pédagogique
    - Le volume horaire à consacrer aux Mimos (ou aux cours pour les sections anglophones)
    - Le volume horaire total qui intègre une estimation minimale du travail personnel à fournir pour réussir
  - l'enseignant référent
  - les prérequis du cours
  - le résumé du cours
  - les dispositifs pédagogiques mobilisés (cours, TD, TP, projets, etc.)
  - les acquis d'apprentissage
  - les modalités d'évaluation
  - la bibliographie.


  ### Validatation
  
  Une UE est validée si la moyenne pondérée de ses ECUE est supérieure ou égale à 10, <b>ET</b> si aucun ECUE qui la compose n'a de note en dessous du seuil.