information:
  label: Informatique Pratique S1
  level: L1
  ects: 6
  coordinator: Martin VAN LAERE

description: |
  ## Introduction
  
  Le but de cette UE est de vous faire découvrir (ou redécouvrir) le monde de la programmation via le langage C#.
  
  L'informatique et plus particulièrement la programmation est devenue une compétence essentielle dans notre société, c'est également une des raisons qui vous a poussé à rejoindre cette école.
  
  Cette UE vise à vous donner les bases nécessaires pour comprendre, créer et résoudre des problèmes d'implémentation.
  
  ### Objectifs
  
  L'objectif principal est de vous familiariser avec les concepts fondamentaux de la programmation en C# et de vous préparer à résoudre des problèmes informatiques du monde réel.
  
  Que vous soyez novice ou que vous ayez déjà une certaine expérience, vous aurez l'occasion de développer vos compétences de manière progressive, tout en explorant les possibilités fascinantes offertes par la programmation.
  
  ### Méthodologie d'enseignement
  
  Ce cours sera interactif et axé sur la pratique. Vous aurez l'occasion de travailler sur des sujets concrets tout au long du semestre, ce qui vous permettra de mettre en pratique les concepts que vous apprendrez en CM. Nous encourageons également la collaboration entre les étudiants, car la programmation est souvent une activité d'équipe dans le monde professionnel.
  
  ### Évaluations
  
  Les évaluations se feront par le biais de travaux pratiques noté de façon automatique par la "moulinette" ainsi que d'examen machine (un tp en conditions d'examen) 
  
  ## Conclusion
  
  N'oubliez pas que la programmation est une compétence qui s'apprend mieux par la pratique, alors préparez-vous à vous plonger dans le code et à explorer les possibilités infinies de la programmation en C#. Bonne chance et amusez-vous bien !
  
  <hr>
  <br>
  
  ### Informations générales
  
  #### Langage de programmation
  - Le langage utilisé pour cette UE est `C#11` sous `.NET7+` uniquement (applicable sur tous les AAVs)
    - Suivant la date de sortie de `C#12`, le contenu des ECUE pourra proposer ces nouveautés.
  
  #### Format des activités
  - Cours Magistraux - 1h par semaine
    - *Le cours magistral peut être remplacé par une remédiation suivant les semaines*
  - Travaux Pratiques - 3h par semaine
  - Travail Personnel - ~6h par semaine
  
  #### Découpage d'un ECUE
  - Un cours ou une remédiation sur chaque semaine
  - 1 semaine de `reload` (sauf premier bimestre)
    - Les étudiants peuvent soumettre à nouveau tous les TP et l'examen de l'ECUE précédent
    - Les notes obtenables sont limitées à 10/20 pour un TP et 08/20 pour un examen
    - L'objectif est de permettre d'éviter un échec de l'ECUE sans pour autant permettre une validation sans utiliser les compensations via les autres ECUE de l'UE
  - 4 semaines de TP (à raison d'un sujet par semaine)
    - Chaque TP va mettre en pratique les nouvelles notions vues en CM précédemment
  - 1 semaine de révision
    - Reprise de toutes les notions de l'ECUE dans un TP permettant une autre approche de celles-ci
  - 1 examen
    - Examen en salle machine d'évaluation des AAVs de l'ECUE
  
  #### Découpage d'un TP
  - la première section contient les AAVs
    - obtenir 100% sur les tests de cette section garantis une note ≥ 12
    - cette partie correspond au temps de travail attendu
  - les deux sections suivantes sont pour ceux qui souhaitent aller plus loin et dépasser les objectifs attendus
    - elles permettent d'atteindre la note maximale, mais ne sont pas requises pour valider l'ECUE
  
  #### Informations complémentaires
  - Les cours précèdent toujours les TP les mettant en pratique
  - Le contenu des TP est incrémental (reprise des notions des TP précédents)